media: media
content:
  - name: pins
    label: Pins
    type: collection
    path: 'content\pins'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: latitude
        label: Latitude
        type: number
        default: 0
        required: true
      - name: longitude
        label: Longitude
        type: number
        default: 0
        required: true
      - name: elevation
        label: Elevation
        type: number
        default: 0
        required: true
      - name: body
        label: Body
        type: rich-text